import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { join } from 'node:path';
import * as schema from './schema';

/**
 * Test-only helper: an in-memory SQLite DB with the real migrations applied
 * (drizzle/ generated by `npm run db:generate`), so unit tests exercise the
 * same schema as production without touching a file on disk. Not imported
 * by any route or `db/index.ts` — those use the file-backed singleton.
 */
export function createTestDb() {
	const sqlite = new Database(':memory:');
	sqlite.pragma('foreign_keys = ON');
	const db = drizzle(sqlite, { schema });
	migrate(db, { migrationsFolder: join(process.cwd(), 'drizzle') });
	return db;
}
